#!/bin/sh

# Environment settings
errorlog="${HOME}/.xerrors"

# Log settings
#
# Always start X11 with a clean log file
if (cp /dev/null "${errorlog}"); then
  chmod 600 "${errorlog}"
  exec >"${errorlog}" 2>&1
fi

# Resource settings
xrdb ${HOME}/.Xresources

## Keyboard control, repeat delay and repeat rate
xset r rate 300 50
##Pointer control, acceleration and threshold
xset m 30/10 4

## Pointer appearance
##   - xcb does not support Xcursor yet
##xsetroot -cursor_name left_ptr

## Keyboard disposition
if [[ "air" == $HOST ]]; then
	. $HOME/.xkb/scripts/load-vimboard-mac
else
	. $HOME/.xkb/scripts/load-vimboard
fi

### programs automatically launched
##[[ -d $HOME/atelier/clavier/xkeyvents ]] && $HOME/atelier/clavier/xkeyvents/logkeys.py

# run all system xinitrc shell scripts.
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for i in /etc/X11/xinit/xinitrc.d/* ; do
		if [ -x "$i" ]; then
			. "$i"
		fi
	done
fi

if uname -a | grep -q DARWIN; then
  exec twm
fi

exec awesome
