# Options
. ~/.zshoptions

# Parameters
. ~/.zshparam
. ~/.zshprompt

# Aliases
. ~/.zshalias

# Zle
. ~/.zshzle

# Completion
. ~/.zshcompsys

# Local
[[ -f ~/.zshrc_local ]] && . ~/.zshrc_local

# show directory content on cd
function chpwd() {
	emulate -LR zsh
	l
}

# artificial intelligence
trap "print; print '$fg[red]'ouch; return" INT

TRAPEXIT() {
	if [[ ! -o login && -r ~/.zlogout ]]; then
		. ~/.zlogout
	fi
}

# keychain
[[ -f ~/.keychain/$HOST-sh ]] && source ~/.keychain/$HOST-sh

# fzf
source /usr/share/fzf/key-bindings.zsh

# zsh local
source ~/.zshrc_local
